- id: '1610520380331'
  alias: Fishtank day
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - device_id: 28d4df6625bc4fdaed286535e55a7bba
    domain: select
    entity_id: select.fishtank_preset
    type: select_option
    option: Day
  mode: single
- id: '1610520452720'
  alias: Fishtank night
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - device_id: 28d4df6625bc4fdaed286535e55a7bba
    domain: select
    entity_id: select.fishtank_preset
    type: select_option
    option: Night
  mode: single
- id: '1614026220990'
  alias: turn on office lights when in office
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: binary_sensor.test_camera_pir
    above: '0'
  condition: []
  action:
  - domain: light
    entity_id: light.office
    device_id: c5793b822f5f378baa39ce239b241153
    type: turn_on
  mode: single
- id: '1627494208126'
  alias: Pool pump start
  description: Turn the Main pool pump on if the heater is not on
  trigger:
  - platform: time
    at: 0:00
  condition:
  - condition: device
    type: is_off
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_1
    domain: switch
  action:
  - type: turn_on
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_2
    domain: switch
  mode: single
- id: '1627494316118'
  alias: Pool pump stop
  description: Turn off the pool pump when sufficient water has been filtered
  trigger:
  - type: value
    platform: device
    device_id: 5ae23a566eda0ad757b32e1baeb1e36c
    entity_id: sensor.daily_flow
    domain: sensor
    above: 8000
  condition:
  - condition: device
    type: is_off
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_1
    domain: switch
  action:
  - type: turn_off
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_2
    domain: switch
  mode: single
- id: '1628113145425'
  alias: bed screen up
  description: ''
  trigger:
  - platform: device
    device_id: 14f6a5afc0a043491406010c89dd919d
    domain: media_player
    entity_id: media_player.sky_q_bedroom
    type: playing
  condition: []
  action:
  - device_id: f6a1f9e41155b73a7d330021e6815e35
    domain: cover
    entity_id: cover.bed_screen
    type: open
  mode: single
- id: '1628113225529'
  alias: bed screen down
  description: ''
  trigger:
  - platform: device
    device_id: 14f6a5afc0a043491406010c89dd919d
    domain: media_player
    entity_id: media_player.sky_q_bedroom
    type: turned_off
  condition: []
  action:
  - device_id: f6a1f9e41155b73a7d330021e6815e35
    domain: cover
    entity_id: cover.bed_screen
    type: close
  mode: single
- id: '1630334936678'
  alias: Fishtank evening
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - device_id: 28d4df6625bc4fdaed286535e55a7bba
    domain: select
    entity_id: select.fishtank_preset
    type: select_option
    option: Evening
  mode: single
- id: '1638922858499'
  alias: Christmas on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  - platform: state
    entity_id: input_boolean.christmas_lights
    to: 'on'
  - platform: time
    at: 07:00
  condition: []
  action:
  - scene: scene.christmas_on
  mode: single
- id: '1638922910713'
  alias: Christmas off
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  - platform: state
    entity_id: input_boolean.christmas_lights
    to: 'off'
  condition: []
  action:
  - scene: scene.christmas_off
  mode: single
- id: '1640167513478'
  alias: Christmas inside
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - scene: scene.christmas_inside
  mode: single
