- id: '1627494208126'
  alias: Pool pump start
  description: Turn the Main pool pump on if the heater is not on
  trigger:
  - platform: time
    at: 0:00
  condition:
  - condition: device
    type: is_off
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_1
    domain: switch
  action:
  - type: turn_on
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_2
    domain: switch
  mode: single
- id: '1627494316118'
  alias: Pool pump stop
  description: Turn off the pool pump when sufficient water has been filtered
  trigger:
  - type: value
    platform: device
    device_id: 5ae23a566eda0ad757b32e1baeb1e36c
    entity_id: sensor.daily_flow
    domain: sensor
    above: 8000
  condition:
  - condition: device
    type: is_off
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_1
    domain: switch
  action:
  - type: turn_off
    device_id: c150f10fc417947965ddcf7d93f11533
    entity_id: switch.socket_2
    domain: switch
  mode: single
- id: '1628113145425'
  alias: Bedroom TV on
  description: ''
  trigger:
  - platform: device
    device_id: 14f6a5afc0a043491406010c89dd919d
    domain: media_player
    entity_id: 8345d906622e29e4aacddf8a694e7853
    type: playing
  condition: []
  action:
  - scene: scene.bedroom_tv_on
  mode: single
- id: '1628113225529'
  alias: Bedroom TV off
  description: ''
  trigger:
  - platform: device
    device_id: 14f6a5afc0a043491406010c89dd919d
    domain: media_player
    entity_id: media_player.sky_q_bedroom
    type: turned_off
  condition: []
  action:
  - scene: scene.bedroom_tv_off
  mode: single
- id: '1638922858499'
  alias: Christmas on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  - platform: state
    entity_id: input_boolean.christmas_lights
    to: 'on'
  - platform: time
    at: 07:00
  condition: []
  action:
  - scene: scene.christmas_on
  mode: single
- id: '1638922910713'
  alias: Christmas off
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  - platform: state
    entity_id: input_boolean.christmas_lights
    to: 'off'
  condition: []
  action:
  - scene: scene.christmas_off
  mode: single
- id: '1640167513478'
  alias: Christmas inside
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - scene: scene.christmas_inside
  mode: single
- id: '1674337992210'
  alias: Turn heating off when away
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.google_home_away
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id:
      - climate.bathroom
      - climate.benedict_room
      - climate.conservatory
      - climate.hive
      - climate.lillis_room
      - climate.master_bedroom
      - climate.tys_room
  mode: single
- id: '1674338354468'
  alias: Turn heating on when at home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.google_home_away
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      entity_id:
      - climate.conservatory
      - climate.master_bedroom
      - climate.tys_room
      - climate.benedict_room
      - climate.lillis_room
  - service: climate.set_hvac_mode
    data:
      hvac_mode: auto
    target:
      entity_id: climate.hive
  mode: single
- id: '1693946035795'
  alias: Turn on pool pump with heater
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.socket_1
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.socket_2
  mode: single
- id: '1693946083586'
  alias: Turn Pool Pump off with heater
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.socket_1
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.socket_2
  mode: single
