# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#homeassistant:
#  external_url: https://home.bigjungle.net:8443
#  internal_url: http://homeassistant.lan:8123

# Text to speech
tts:
  - platform: google_translate

stream:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - ::1

recorder:
  purge_keep_days: 30

climate:
  - unique_id: pool_heater_thermostat
    platform: generic_thermostat
    name: Pool heater
    heater: switch.socket_1
    target_sensor: sensor.pool_temperature_temperature
    cold_tolerance: 1
    min_cycle_duration:
      minutes: 5
    min_temp: 18
    max_temp: 40
    precision: 0.5

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
