- platform: mqtt
  unique_id: switch_plug1
  name: "Christmas Tree"
  state_topic: "sonoff/plug1/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "sonoff/plug1/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability:
    topic: "sonoff/plug1/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  qos: 1
  retain: false
