substitutions:
  name: esp32-s3-box-3-05ab90
  friendly_name: ESP32 S3 Box 3 05ab90
packages:
  #esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main\
  esphome.voice-assistant: github://jeremypoulter/ESP32-S3-Box-3-Voice-Assistant-Sensor-Dock/esp32-s3-box-3.yaml@master\
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: fjhjScEWJuY8DiZrzIwdZv/sw9nEAUJ6/m5XnYvfCOk=

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
