substitutions:
  device_name: "espdisplay"
  friendly_name: "eInk Display"

esphome:
  name: $device_name
  platform: ESP32
  board: esp-wrover-kit

  wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret hotspot_wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
