substitutions:
  device_name: "fishtank"
  friendly_name: "Fishtank"

esphome:
  name: $device_name

platform: ESP8266
  board: huzzah

  wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret hotspot_wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  - pin: GPIO5

# Individual sensors
sensor:
  - platform: dallas
    name: "$friendly_name Temperature"
    index: 0

light:
  - platform: fastled_spi
    chipset: P9813
    data_pin: GPIO2
    clock_pin: GPIO12
    num_leds: 1
    rgb_order: GRB
    name: "$friendly_name Light"

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time
