# Substitutions
substitutions:
  # Device Names
  device_name: "poolmon"
  friendly_name: "Pool Monitor"

esphome:
  name: "${device_name}"

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ext
    password: !secret wifi_password
  domain: .lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret hotspot_wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
#    on_time:
#      # reset the pulse counter every night
#      - seconds: 0
#        minutes: 0
#        hours: 0
#        then:
#          - pulse_meter.set_total_pulses:
#              id: flow
#              value: 0

# Device Specific Config
binary_sensor:
  # Push Button (Toggles All Relays When Pressed)
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"

one_wire:
  - platform: gpio
    pin: GPIO18
  
esp32_ble_tracker:

bluetooth_proxy:
  active: true

sensor:
  # WiFi Signal Sensor
  - platform: wifi_signal
    name: "${friendly_name} WiFi Status"
    update_interval: 60s

  - platform: dallas_temp
    address: 0x79000005E4BC3928
    name: "In Temperature"

  - platform: dallas_temp
    address: 0x67000007FFEF2528
    name: "Out Temperature"

  - platform: dallas_temp
    address: 0xB5000005E58E4D28
    name: "External Temperature"

  - platform: pulse_counter
    id: flow
    pin: GPIO25
    name: 'Flow rate'
    unit_of_measurement: 'L/hour'
    #timeout: 1s
    filters:
      #- sliding_window_moving_average:
      #    window_size: 50
      #    send_every: 50
      - lambda: return ((x * 60) / 27.0);
      #- multiply: 0.222222222  # (60/270 pulses per l)
    accuracy_decimals: 0
    total:
      unit_of_measurement: 'L'
      name: 'Total flow'
      filters:
        #- sliding_window_moving_average:
        #    window_size: 15
        #    send_every: 15
        - lambda: return (x / 27.0);
        #- multiply: 0.003703704  # (1/270 pulses per L)

  - platform: total_daily_energy
    name: "Daily flow"
    power_id: flow
    unit_of_measurement: 'L'

  - platform: inkbird_ibsth1_mini
    mac_address: "49:24:03:06:04:19"
    temperature:
      name: "Pool Temperature"
    battery_level:
      name: "Pool Temperature Battery Level"

status_led:
  pin:
    number: GPIO02
    inverted: true

